### ISSUE TITLE
Fail to bootstrap a new project

### ISSUE THREAD

**Issue by untilbit** [TypedProject/ts-express-decorators#3232]
### Describe the bug

Errors when generating a new project using NPX and BUNX.

### To Reproduce

```sh
bunx -p @tsed/cli tsed init example-app
? What is your project name example-app
? Choose the target Framework: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project Database, Passport.js, Documentation, Testing, Linter
? Choose a documentation plugin Scalar
? Choose a ORM manager Prisma
? Choose unit framework Vitest
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier, Lint on commit
? Choose the runtime: Bun.js
↓ Write RC files
✔ Initialize package.json
✔ Install plugins
⠋ Load plugins
↓ Write RC files
✔ Initialize package.json
✔ Install plugins
✔ Load plugins
✔ Install plugins dependencies
✔ Generate project files
✔ Generate Prisma schema
✔ Add Ts.ED configuration to Prisma schema
✔ Generate files for eslint
✔ Add dependencies
✔ Generate files for vitest
✔ Install dependencies
✔ Add husky prepare task
✔ Run linter
✔ Generate barrels files
file:///tmp/bunx-1000-@tsed/cli@latest/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: bun run prisma:generate
$ bun x prisma generate
Loaded Prisma config from prisma.config.ts.

Prisma schema loaded from prisma/schema.prisma.
Error: Generator "Ts.ED integration" requires generator "prisma-client-js", but it is missing in your schema.prisma.
Please add it to your schema.prisma:

generator gen {
  provider = "prisma-client-js"
}

error: script "prisma:generate" exited with code 1
    at makeError (file:///tmp/bunx-1000-@tsed/cli@latest/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///tmp/bunx-1000-@tsed/cli@latest/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  shortMessage: 'Command failed with exit code 1: bun run prisma:generate',
  command: 'bun run prisma:generate',
  escapedCommand: 'bun run "prisma:generate"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '$ bun x prisma generate\n' +
    'Loaded Prisma config from prisma.config.ts.\n' +
    '\n' +
    'Prisma schema loaded from prisma/schema.prisma.\n' +
    'Error: Generator "Ts.ED integration" requires generator "prisma-client-js", but it is missing in your schema.prisma.\n' +
    'Please add it to your schema.prisma:\n' +
    '\n' +
    'generator gen {\n' +
    '  provider = "prisma-client-js"\n' +
    '}\n' +
    '\n' +
    'error: script "prisma:generate" exited with code 1',
  cwd: '/home/tsed/example-app',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v24.9.0
```

### Expected behavior

A new project should be scafollded without issues.

### Code snippets

```TypeScript

```

### OS

Linux

### Node version

Node v24.9.0

### Library version

v8

**Comment by Romakita** [comment]
Can you try with`npm i -g @tsed/cli@rc`. I'll take to fix if the problem persist

**Comment by itea-dev** [comment]
It still fails
```

[23532:0xd08e000]    80862 ms: Scavenge (interleaved) 4087.6 (4101.3) -> 4085.7 (4110.3) MB, pooled: 0 MB, 11.93 / 0.00 ms  (average mu = 0.148, current mu = 0.022) allocation failure; 
[23532:0xd08e000]    81901 ms: Mark-Compact (reduce) 4093.1 (4111.1) -> 4091.1 (4101.9) MB, pooled: 0 MB, 32.31 / 0.00 ms  (+ 567.8 ms in 113 steps since start of marking, biggest step 5.0 ms, walltime since start of marking 669 ms) (average mu = 0.301, c
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xf4db93 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x13b24d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0x13b25bf v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x164b0a5  [node]
 5: 0x165c22c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 6: 0x1631e93 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 7: 0x1607b30 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 8: 0x1afd938 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x76fe03e76636 
Aborted (core dumped)
```

**Comment by Romakita** [comment]
fixed with the latest rc version `npm i -g @tsed/cli@rc`

**Comment by Romakita** [comment]
<img width="1123" height="511" alt="Image" src="https://github.com/user-attachments/assets/6b642922-987c-4981-9f6f-52ed8bd264ba" />

**Comment by itea-dev** [comment]
It still fails.

Here is the full output.
```
tsed init app-tsed
│
◇  What is your project name
│  app-tsed
│
◇  Choose the target Framework:
│  Express.js
│
◇  Choose the architecture for your project:
│  Ts.ED
│
◇  Choose the convention file styling:
│  Ts.ED
│
◇  Choose the features needed for your project
│  Configuration sources, Documentation, Linter, Database, Passport.js, Testing
│
◇  Choose configuration sources
│  Envs, JSON
│
◇  Choose a documentation plugin
│  Swagger, Scalar
│
◇  Choose a ORM manager
│  Prisma
│
◇  Which passport package ?
│  passport-amigame - OAuth2 client authentication for Amigame using passport.js
│
◇  Choose unit framework
│  Vitest
│
◇  Choose linter tools framework
│  EsLint
│
◇  Choose extra linter tools
│  Prettier
│
◇  Choose the runtime:
│  Bun.js
│
▲  Write RC files skipped...
│
●  Initialize package.json...
│
◆  Initialize package.json completed
│
◇  Install plugins completed
│
●  Load plugins...
│
●  Load plugins - Try to load @tsed/cli-plugin-eslint
│
●  Load plugins - Try to load @tsed/cli-plugin-passport
│
●  Load plugins - Try to load @tsed/cli-plugin-prisma
│
●  Load plugins - Try to load @tsed/cli-plugin-vitest
│
●  Load plugins - @tsed/cli-plugin-prisma module loaded
│
●  Load plugins - @tsed/cli-plugin-passport module loaded
│
●  Load plugins - @tsed/cli-plugin-eslint module loaded
│
●  Load plugins - @tsed/cli-plugin-vitest module loaded
│
◆  Load plugins completed
│
●  Install plugins dependencies...
│
◆  Run plugin '@tsed/cli-plugin-eslint' completed
│
◆  Run plugin '@tsed/cli-plugin-passport' completed
│
◆  Run plugin '@tsed/cli-plugin-prisma' completed
│
◆  Run plugin '@tsed/cli-plugin-vitest' completed
│
◇  Install dependencies completed
│
◆  Install plugins dependencies completed
│
●  Render base files...
│
◆  Render base files completed
│
●  Alter package json...
│
●  Alter package json - Alter package.json dependencies by eslint plugin
│
◆  Alter package json completed
│
●  Generate additional project files...
│
◆  Generate controller file to 'src/controllers/rest/HelloWorldController.ts' completed
│
◆  Transform generated files completed
│
◆  Generate controller spec file to 'src/controllers/rest/HelloWorldController.spec.ts' completed
│
◆  Generate controller integration file 'src/controllers/rest/HelloWorldController.integration.spec.ts' completed
│
◇  Generate Prisma schema
│
│
◆  Generate Prisma schema completed
│
◆  Add Ts.ED configuration to Prisma schema completed
│
◆  Add eslint configuration completed
│
◆  Create vitest configuration completed
│
◆  Generate additional project files completed
│
●  transform generated files to the project configuration...
│
◆  transform generated files to the project configuration completed
│
◇  Install dependencies completed
│
▲  Add husky prepare task skipped...
│
●  Run linter...
│
│  Run linter - $ eslint --fix
│
◆  Run linter completed
│
◇  Check installed dependencies completed
│
●  Generate barrels files...
│
│  Generate barrels files - $ barrels
│
◆  Generate barrels files completed
file:///home/tsedhome/.local/share/fnm/node-versions/v24.9.0/installation/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: bun run prisma:generate
$ bun x prisma generate
Error: Could not find Prisma Schema that is required for this command.
You can either provide it with `--schema` argument,
set it in your Prisma Config file (e.g., `prisma.config.ts`),
set it as `prisma.schema` in your package.json,
or put it into the default location (`./prisma/schema.prisma`, or `./schema.prisma`.
Checked following paths:

schema.prisma: file not found
prisma/schema.prisma: file not found

See also https://pris.ly/d/prisma-schema-location
error: script "prisma:generate" exited with code 1
    at makeError (file:///home/tsedhome/.local/share/fnm/node-versions/v24.9.0/installation/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/tsedhome/.local/share/fnm/node-versions/v24.9.0/installation/lib/node_modules/@tsed/cli/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  shortMessage: 'Command failed with exit code 1: bun run prisma:generate',
  command: 'bun run prisma:generate',
  escapedCommand: 'bun run "prisma:generate"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '$ bun x prisma generate\n' +
    'Error: Could not find Prisma Schema that is required for this command.\n' +
    'You can either provide it with `--schema` argument,\n' +
    'set it in your Prisma Config file (e.g., `prisma.config.ts`),\n' +
    'set it as `prisma.schema` in your package.json,\n' +
    'or put it into the default location (`./prisma/schema.prisma`, or `./schema.prisma`.\n' +
    'Checked following paths:\n' +
    '\n' +
    'schema.prisma: file not found\n' +
    'prisma/schema.prisma: file not found\n' +
    '\n' +
    'See also https://pris.ly/d/prisma-schema-location\n' +
    'error: script "prisma:generate" exited with code 1',
  cwd: '/home/tsedhome/workspace/app-tsed',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v24.9.0

``

**Comment by Romakita** [comment]
The main difference is bun. Are sure you are on rc3 ? Because you should have a prompt from prisma cli to configure region and prisma account.
Maybe bunx isn’t appropriate to run prisma cli.

**Comment by itea-dev** [comment]
Last time I used npx. I might give it another try later.

**Comment by Romakita** [comment]
npm i -g @tsed/cli@rc
tsed init .
